### ISSUE TITLE
Error when Running LLMReplayStrategyMixin

### ISSUE THREAD

**Issue by FFFiend** [MLDSAI/OpenAdapt#117]
Upon running this command to take the LLMStrategy out for a spin: python -m puterbot.replay LLMReplayStrategyMixin

I encounter the following error:
```
(.venv) PS C:\Users\owais\OneDrive\Desktop\PUTERBOT\OpenAdapt> python -m puterbot.replay LLMReplayStrategyMixin
2023-05-08 07:51:56.770 | INFO     | __main__:replay:19 - strategy_name='LLMReplayStrategyMixin'
2023-05-08 07:51:57.761 | INFO     | __main__:replay:34 - strategy_class=<class 'puterbot.strategies.llm_mixin.LLMReplayStrategyMixin'>
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\owais\OneDrive\Desktop\PUTERBOT\OpenAdapt\puterbot\replay.py", line 43, in <module>
    fire.Fire(replay)
  File "C:\Users\owais\OneDrive\Desktop\PUTERBOT\OpenAdapt\.venv\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\owais\OneDrive\Desktop\PUTERBOT\OpenAdapt\.venv\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\owais\OneDrive\Desktop\PUTERBOT\OpenAdapt\.venv\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\owais\OneDrive\Desktop\PUTERBOT\OpenAdapt\puterbot\replay.py", line 36, in replay
    strategy = strategy_class(recording)
TypeError: Can't instantiate abstract class LLMReplayStrategyMixin with abstract method get_next_input_event
```

I've followed all the required setup steps, additionally I also cannot visualize as I encounter the same indexing error as #94.

**Comment by abrichr** [comment]
The error is expected behavior. The LLMReplayStrategyMixin is not intended to be run directly. See https://en.wikipedia.org/wiki/Mixin for more information about this pattern.
