### ISSUE TITLE
Error `alembic upgrade head` gives error

### ISSUE THREAD

**Issue by KrishPatel13** [MLDSAI/OpenAdapt#237]
Running `alembic upgrade head` gives this error: 
```
(.venv) PS P:\OpenAdapt AI - MLDS AI\cloned_repo\OpenAdapt> alembic upgrade head
2023-06-08 19:43:46.740 | INFO     | openadapt.config:<module>:61 - CACHE_DIR_PATH=.cache
2023-06-08 19:43:46.744 | INFO     | openadapt.config:<module>:61 - CACHE_ENABLED=True 
2023-06-08 19:43:46.747 | INFO     | openadapt.config:<module>:61 - CACHE_VERBOSITY=0  
2023-06-08 19:43:46.749 | INFO     | openadapt.config:<module>:61 - DB_ECHO=False      
2023-06-08 19:43:46.750 | INFO     | openadapt.config:<module>:61 - DB_FNAME=openadapt.db
2023-06-08 19:43:46.751 | INFO     | openadapt.config:<module>:61 - OPENAI_API_KEY=<set your api key in .env>
2023-06-08 19:43:46.753 | INFO     | openadapt.config:<module>:61 - OPENAI_MODEL_NAME=gpt-3.5-turbo
2023-06-08 19:43:46.755 | INFO     | openadapt.config:<module>:61 - RECORD_READ_ACTIVE_ELEMENT_STATE=False
2023-06-08 19:43:46.757 | INFO     | openadapt.config:<module>:61 - REPLAY_STRIP_ELEMENT_STATE=True
2023-06-08 19:43:46.759 | INFO     | openadapt.config:<module>:61 - ACTION_TEXT_SEP=-
2023-06-08 19:43:46.761 | INFO     | openadapt.config:<module>:61 - ACTION_TEXT_NAME_PREFIX=<
2023-06-08 19:43:46.762 | INFO     | openadapt.config:<module>:61 - ACTION_TEXT_NAME_SUFFIX=>
2023-06-08 19:43:46.763 | INFO     | openadapt.config:<module>:61 - ROOT_DIRPATH=P:\OpenAdapt AI - MLDS AI\cloned_repo\OpenAdapt
2023-06-08 19:43:46.765 | INFO     | openadapt.config:<module>:61 - DB_FPATH=P:\OpenAdapt AI - MLDS AI\cloned_repo\OpenAdapt\openadapt.db
2023-06-08 19:43:46.766 | INFO     | openadapt.config:<module>:61 - DB_URL=sqlite:///P:\OpenAdapt AI - MLDS AI\cloned_repo\OpenAdapt\openadapt.db
2023-06-08 19:43:46.767 | INFO     | openadapt.config:<module>:61 - DIRNAME_PERFORMANCE_PLOTS=performance
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main     
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "P:\OpenAdapt AI - MLDS AI\cloned_repo\OpenAdapt\.venv\Scripts\alembic.exe\__main__.py", line 7, in <module>
  File "P:\OpenAdapt AI - MLDS AI\cloned_repo\OpenAdapt\.venv\lib\site-packages\alembic\config.py", line 590, in main
    CommandLine(prog=prog).main(argv=argv)
  File "P:\OpenAdapt AI - MLDS AI\cloned_repo\OpenAdapt\.venv\lib\site-packages\alembic\config.py", line 584, in main
    self.run_cmd(cfg, options)
  File "P:\OpenAdapt AI - MLDS AI\cloned_repo\OpenAdapt\.venv\lib\site-packages\alembic\config.py", line 561, in run_cmd
    fn(
  File "P:\OpenAdapt AI - MLDS AI\cloned_repo\OpenAdapt\.venv\lib\site-packages\alembic\command.py", line 322, in upgrade
    script.run_env()
  File "P:\OpenAdapt AI - MLDS AI\cloned_repo\OpenAdapt\.venv\lib\site-packages\alembic\script\base.py", line 569, in run_env
    util.load_python_file(self.dir, "env.py")
  File "P:\OpenAdapt AI - MLDS AI\cloned_repo\OpenAdapt\.venv\lib\site-packages\alembic\util\pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "P:\OpenAdapt AI - MLDS AI\cloned_repo\OpenAdapt\.venv\lib\site-packages\alembic\util\pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "P:\OpenAdapt AI - MLDS AI\cloned_repo\OpenAdapt\alembic\env.py", line 92, in <module>
    run_migrations_online()
  File "P:\OpenAdapt AI - MLDS AI\cloned_repo\OpenAdapt\alembic\env.py", line 70, in run_migrations_online
    configuration = config.get_section(config.config_ini_section)
AttributeError: module 'openadapt.config' has no attribute 'get_section'
```

**Comment by 0dm** [comment]
fixed in #238
