### ISSUE TITLE
Support other spacy models

### ISSUE THREAD

**Issue by abrichr** [MLDSAI/OpenAdapt#317]
### Feature request

Setting `model_name` to `en_core_web_lg` in `config.py` yields the following error:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/abrichr/oa/OpenAdapt/openadapt/scripts/scrub.py", line 33, in <module>
    from openadapt import config, scrub, utils
  File "/Users/abrichr/oa/OpenAdapt/openadapt/scrub.py", line 27, in <module>
    NLP_ENGINE_TRF = SCRUB_PROVIDER_TRF.create_engine()
  File "/Users/abrichr/Library/Caches/pypoetry/virtualenvs/openadapt-VBXg4jpm-py3.10/lib/python3.10/site-packages/presidio_analyzer/nlp_engine/nlp_engine_provider.py", line 91, in create_engine
    engine = nlp_engine_class(nlp_engine_opts)
  File "/Users/abrichr/Library/Caches/pypoetry/virtualenvs/openadapt-VBXg4jpm-py3.10/lib/python3.10/site-packages/presidio_analyzer/nlp_engine/spacy_nlp_engine.py", line 36, in __init__
    self.nlp = {
  File "/Users/abrichr/Library/Caches/pypoetry/virtualenvs/openadapt-VBXg4jpm-py3.10/lib/python3.10/site-packages/presidio_analyzer/nlp_engine/spacy_nlp_engine.py", line 37, in <dictcomp>
    lang_code: spacy.load(model_name, disable=["parser"])
  File "/Users/abrichr/Library/Caches/pypoetry/virtualenvs/openadapt-VBXg4jpm-py3.10/lib/python3.10/site-packages/spacy/__init__.py", line 54, in load
    return util.load_model(
  File "/Users/abrichr/Library/Caches/pypoetry/virtualenvs/openadapt-VBXg4jpm-py3.10/lib/python3.10/site-packages/spacy/util.py", line 449, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_lg'. It doesn't seem to be a Python package or a valid path to a data directory.
```

### Motivation

Scrubbing images can yield significant false negatives. As per https://github.com/microsoft/presidio/issues/862#issuecomment-1121135619 , this may be improved using `en_core_web_lg`.

**Comment by KrishPatel13** [comment]
@abrichr This is because it is not downloaded yet.

Please give me some time, I will respond why we need trf instead of lg model.

**Comment by KrishPatel13** [comment]
To support other model just by changing the model name, we would need to download all of the models in advance during setup of OpenAdapt. 

For eg. if we want a system where we want to switch between en_core_web_lg and en_core_web_trf then we would need to download both of them during the poetry install and then we can freely switch around.

**Comment by KrishPatel13** [comment]
@abrichr How do we want to proceed from here ?

**Comment by 0dm** [comment]
maybe we can install the models via subprocess command if the user specifies a different one?

**Comment by KrishPatel13** [comment]
@abrichr Shall I proceed with this approach ?
