### ISSUE TITLE
Cant install homebrew

### ISSUE THREAD

**Issue by Jonathan-Sendsen** [MLDSAI/OpenAdapt#95]
<img width="762" alt="Screenshot 2023-05-06 at 7 40 34 PM" src="https://user-images.githubusercontent.com/38477076/236649209-200ed85a-a277-4eee-9e7d-722a128d4d6f.png">

**Comment by Jonathan-Sendsen** [comment]
@abrichr 

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
#__conda_setup="$('/Users/jonathansendsen/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
# if [ $? -eq 0 ]; then
#     eval "$__conda_setup"
# else
#     if [ -f "/Users/jonathansendsen/anaconda3/etc/profile.d/conda.sh" ]; then
#         . "/Users/jonathansendsen/anaconda3/etc/profile.d/conda.sh"
#     else
#         export PATH="/Users/jonathansendsen/anaconda3/bin:$PATH"
#     fi
# fi
# unset __conda_setup
# <<< conda initialize <<<

**Comment by Jonathan-Sendsen** [comment]
``` 
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.1.0-cp310-cp310-macosx_10_9_x86_64.whl (124 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.0.2-py3-none-any.whl (123 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting mpmath>=0.19
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Collecting parso<0.9.0,>=0.8.0
  Using cached parso-0.8.3-py2.py3-none-any.whl (100 kB)
Collecting ptyprocess>=0.5
  Using cached ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting wcwidth
  Using cached wcwidth-0.2.6-py2.py3-none-any.whl (29 kB)
Collecting humanfriendly>=9.1
  Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Collecting executing>=1.2.0
  Using cached executing-1.2.0-py2.py3-none-any.whl (24 kB)
Collecting pure-eval
  Using cached pure_eval-0.2.2-py3-none-any.whl (11 kB)
Collecting asttokens>=2.1.0
  Using cached asttokens-2.2.1-py2.py3-none-any.whl (26 kB)
Building wheels for collected packages: pynput
  Building wheel for pynput (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      /Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/33/g_h_rt791rvdrpm4xrhbn_8r0000gn/T/pip-req-build-zn0v_x_c/setup.py", line 87, in <module>
          setuptools.setup(
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 875, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1087, in obtain
          return installer(requirement)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 945, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
          wheel.install_as_egg(dist_location)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 110, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 118, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 162, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/var/folders/33/g_h_rt791rvdrpm4xrhbn_8r0000gn/T/pip-req-build-zn0v_x_c/.eggs/charset_normalizer-3.1.0-py3.10-macosx-10.9-universal2.egg/charset_normalizer-3.1.0.dist-info' -> '/private/var/folders/33/g_h_rt791rvdrpm4xrhbn_8r0000gn/T/pip-req-build-zn0v_x_c/.eggs/charset_normalizer-3.1.0-py3.10-macosx-10.9-universal2.egg/EGG-INFO'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pynput
  Running setup.py clean for pynput
  error: subprocess-exited-with-error
  
  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      /Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/33/g_h_rt791rvdrpm4xrhbn_8r0000gn/T/pip-req-build-zn0v_x_c/setup.py", line 87, in <module>
          setuptools.setup(
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 875, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1087, in obtain
          return installer(requirement)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 945, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
          wheel.install_as_egg(dist_location)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 110, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 118, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 162, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/var/folders/33/g_h_rt791rvdrpm4xrhbn_8r0000gn/T/pip-req-build-zn0v_x_c/.eggs/charset_normalizer-3.1.0-py3.10-macosx-10.9-universal2.egg/charset_normalizer-3.1.0.dist-info' -> '/private/var/folders/33/g_h_rt791rvdrpm4xrhbn_8r0000gn/T/pip-req-build-zn0v_x_c/.eggs/charset_normalizer-3.1.0-py3.10-macosx-10.9-universal2.egg/EGG-INFO'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for pynput
Failed to build pynput
```

**Comment by Jonathan-Sendsen** [comment]
After installing ```pynput``` 

I got this output:

``` Collecting pynput
  Using cached pynput-1.7.6-py2.py3-none-any.whl (89 kB)
Collecting six (from pynput)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting pyobjc-framework-ApplicationServices>=8.0 (from pynput)
  Downloading pyobjc_framework_ApplicationServices-9.1.1-cp311-cp311-macosx_10_9_universal2.whl (32 kB)
Collecting pyobjc-framework-Quartz>=8.0 (from pynput)
  Downloading pyobjc_framework_Quartz-9.1.1-cp311-cp311-macosx_10_9_universal2.whl (228 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 228.4/228.4 kB 4.7 MB/s eta 0:00:00
Collecting pyobjc-core>=9.1.1 (from pyobjc-framework-ApplicationServices>=8.0->pynput)
  Downloading pyobjc_core-9.1.1-cp311-cp311-macosx_10_9_universal2.whl (730 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 730.2/730.2 kB 14.1 MB/s eta 0:00:00
Collecting pyobjc-framework-Cocoa>=9.1.1 (from pyobjc-framework-ApplicationServices>=8.0->pynput)
  Downloading pyobjc_framework_Cocoa-9.1.1-cp311-cp311-macosx_10_9_universal2.whl (390 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 390.5/390.5 kB 9.7 MB/s eta 0:00:00
Installing collected packages: six, pyobjc-core, pyobjc-framework-Cocoa, pyobjc-framework-Quartz, pyobjc-framework-ApplicationServices, pynput
Successfully installed pynput-1.7.6 pyobjc-core-9.1.1 pyobjc-framework-ApplicationServices-9.1.1 pyobjc-framework-Cocoa-9.1.1 pyobjc-framework-Quartz-9.1.1 six-1.16.0```

 pynput package and its dependencies have been successfully installed in my Python environment

**Comment by Jonathan-Sendsen** [comment]
Here is my entire log with ChatGPT:

```Homebrew SSL Certificate Error
______________________________

Human: I am trying to install homebrew on my computer when I run the script on homebrews website in my terminal I get this error:

curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

ChatGPT: This error occurs when curl can't verify the SSL certificate of the server it's trying to connect to. You can try a few different solutions to resolve this issue.Warning: Disabling SSL verification can expose you to security risks, such as man-in-the-middle attacks. Proceed with caution and only use these methods if you trust the source of the script.Temporarily bypass SSL certificate verification:
You can use the -k or --insecure flag to bypass the SSL certificate verification. This should only be used if you trust the source of the script. The command would look like this:bashCopy code/bin/bash -c "$(curl -fsSLk https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
Update your CA certificates:
It's possible that your system's CA certificates are outdated. You can try updating them, which may resolve the issue. On macOS, you can use the following command to update CA certificates:cssCopy codesudo softwareupdate --install -a
On Linux, the command to update CA certificates depends on your distribution. For Ubuntu and Debian-based systems, you can use:sqlCopy codesudo apt-get update && sudo apt-get upgrade ca-certificates
For CentOS and RHEL-based systems, you can use:sqlCopy codesudo yum update ca-certificates
Manually download the Homebrew installation script:
If you still have issues, you can manually download the script, review it, and then run it. Use the following commands:bashCopy codecurl -O -J -L --insecure https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
After downloading the script, review it to ensure it's safe to run. Then, execute the script with:bashCopy code/bin/bash install.sh
Please be cautious when working with insecure connections, and only use these methods if you trust the source of the script.
Human: I am trying to install homebrew. When I take this snippet of code:

$ brew install wget


I get this message on my terminal:
zsh: command not found: $

How do I get git on my local machine?
ChatGPT: It seems you're trying to install wget using Homebrew, but the command you're using includes an unnecessary $ symbol, which is causing the error. The $ symbol is commonly used to indicate the command prompt in tutorials and documentation but should not be included in the actual command.To install wget using Homebrew, run the following command:Copy codebrew install wget
As for installing Git, you can also use Homebrew to do this. Once Homebrew is installed, run:Copy codebrew install git
This will install Git on your local machine. If you haven't installed Homebrew yet, follow the instructions provided in my previous response to install Homebrew first.
Human: I am trying to download and install puterbot. When I run this script in my terminal:

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/OpenAdaptAI/install/HEAD/install_puterbot.sh)"


I get this error:
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
ChatGPT: The error you are encountering is caused by curl being unable to verify the SSL certificate of the server it's trying to connect to. As mentioned in my previous response, there are a few ways to address this issue.Warning: Disabling SSL verification can expose you to security risks, such as man-in-the-middle attacks. Proceed with caution and only use these methods if you trust the source of the script.Temporarily bypass SSL certificate verification:
You can use the -k or --insecure flag to bypass the SSL certificate verification. This should only be used if you trust the source of the script. The command would look like this:bashCopy code/bin/bash -c "$(curl -fsSLk https://raw.githubusercontent.com/OpenAdaptAI/install/HEAD/install_puterbot.sh)"
Update your CA certificates:
It's possible that your system's CA certificates are outdated. You can try updating them, which may resolve the issue. On macOS, you can use the following command to update CA certificates:cssCopy codesudo softwareupdate --install -a
On Linux, the command to update CA certificates depends on your distribution. For Ubuntu and Debian-based systems, you can use:sqlCopy codesudo apt-get update && sudo apt-get upgrade ca-certificates
For CentOS and RHEL-based systems, you can use:sqlCopy codesudo yum update ca-certificates
Manually download the Puterbot installation script:
If you still have issues, you can manually download the script, review it, and then run it. Use the following commands:bashCopy codecurl -O -J -L --insecure https://raw.githubusercontent.com/OpenAdaptAI/install/HEAD/install_puterbot.sh
After downloading the script, review it to ensure it's safe to run. Then, execute the script with:bashCopy code/bin/bash install_puterbot.sh
Please be cautious when working with insecure connections, and only use these methods if you trust the source of the script.
Human: I am trying to run this command in my terminal:

python -m puterbot.record "testing out puterbot"

But when I run it I get this error:

 File "/Users/jonathansendsen/anaconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/jonathansendsen/anaconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/jonathansendsen/Desktop/puterbot/puterbot/record.py", line 21, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'

What does it mean?
ChatGPT: The error you're encountering is caused by the missing loguru module, which is a dependency of the Puterbot script you're trying to run. The ModuleNotFoundError indicates that Python couldn't find the required module in your current environment.To resolve this issue, you need to install the loguru module. You can do this using pip, the Python package manager. Run the following command in your terminal:bashCopy codepip install loguru
Once the installation is complete, you should be able to run the Puterbot command without encountering the error:bashCopy codepython -m puterbot.record "testing out puterbot"
If you still face issues, it's possible that there might be a conflict between the Python environments (system Python, Anaconda, or virtual environments). In this case, make sure you're using the correct Python interpreter and pip executable associated with the environment where Puterbot is installed.
Human: After installing loguru I now get this error:

Traceback (most recent call last):
  File "/Users/jonathansendsen/anaconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/jonathansendsen/anaconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/jonathansendsen/Desktop/puterbot/puterbot/record.py", line 22, in <module>
    from pynput import keyboard, mouse
ModuleNotFoundError: No module named 'pynput'
ChatGPT: The new error you're encountering is similar to the previous one. This time, the pynput module is missing, which is another dependency of the Puterbot script. To resolve this issue, you need to install the pynput module using pip. Run the following command in your terminal:bashCopy codepip install pynput
After the installation is complete, you should be able to run the Puterbot command without encountering the error:bashCopy codepython -m puterbot.record "testing out puterbot"
If you continue to encounter errors related to missing modules, you can try installing them one by one using pip install <module_name>. However, it's a good idea to check if Puterbot has a requirements.txt file, which lists all the required dependencies. If it does, you can install all dependencies at once using:bashCopy codepip install -r requirements.txt
Make sure to run this command in the directory where the requirements.txt file is located.
Human: When running this command:
python -m puterbot.visualize

I get this error:
Traceback (most recent call last):
  File "/Users/jonathansendsen/anaconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/jonathansendsen/anaconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/jonathansendsen/Desktop/puterbot/puterbot/visualize.py", line 226, in <module>
    main()
  File "/Users/jonathansendsen/Desktop/puterbot/puterbot/visualize.py", line 135, in main
    input_events = get_events(recording, process=PROCESS_EVENTS, meta=meta)
  File "/Users/jonathansendsen/Desktop/puterbot/puterbot/events.py", line 30, in get_events
    screenshots = get_screenshots(recording)
  File "/Users/jonathansendsen/Desktop/puterbot/puterbot/crud.py", line 109, in get_screenshots
    screenshots[0].prev = screenshots[0]
IndexError: list index out of range

What does it mean?

ChatGPT: The error you're encountering is an IndexError with the message "list index out of range." This error occurs when you try to access an element in a list using an index that is outside the valid range of indices for that list. In this specific case, it's happening on this line of code:pythonCopy codescreenshots[0].prev = screenshots[0]
The error suggests that the screenshots list is empty, so trying to access the first element using screenshots[0] results in an IndexError.To resolve this issue, you might want to check if the Puterbot script is configured correctly and that it has the necessary data (screenshots, in this case) to process. If you're not sure about the configuration or data requirements, you may want to consult the Puterbot documentation or reach out to the developers for support.As a temporary workaround, you can add a check to ensure the list is not empty before accessing its elements. You can modify the line causing the error like this:pythonCopy codeif screenshots:
    screenshots[0].prev = screenshots[0]
This change will only execute the assignment if the screenshots list is not empty, preventing the IndexError. However, this may not address the underlying issue of why the screenshots list is empty in the first place, so it's still essential to check the script configuration and data requirements.
Human: I am getting this error:

Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.1.0-cp310-cp310-macosx_10_9_x86_64.whl (124 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.0.2-py3-none-any.whl (123 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting mpmath>=0.19
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Collecting parso<0.9.0,>=0.8.0
  Using cached parso-0.8.3-py2.py3-none-any.whl (100 kB)
Collecting ptyprocess>=0.5
  Using cached ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting wcwidth
  Using cached wcwidth-0.2.6-py2.py3-none-any.whl (29 kB)
Collecting humanfriendly>=9.1
  Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Collecting executing>=1.2.0
  Using cached executing-1.2.0-py2.py3-none-any.whl (24 kB)
Collecting pure-eval
  Using cached pure_eval-0.2.2-py3-none-any.whl (11 kB)
Collecting asttokens>=2.1.0
  Using cached asttokens-2.2.1-py2.py3-none-any.whl (26 kB)
Building wheels for collected packages: pynput
  Building wheel for pynput (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      /Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/33/g_h_rt791rvdrpm4xrhbn_8r0000gn/T/pip-req-build-zn0v_x_c/setup.py", line 87, in <module>
          setuptools.setup(
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 875, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1087, in obtain
          return installer(requirement)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 945, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
          wheel.install_as_egg(dist_location)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 110, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 118, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 162, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/var/folders/33/g_h_rt791rvdrpm4xrhbn_8r0000gn/T/pip-req-build-zn0v_x_c/.eggs/charset_normalizer-3.1.0-py3.10-macosx-10.9-universal2.egg/charset_normalizer-3.1.0.dist-info' -> '/private/var/folders/33/g_h_rt791rvdrpm4xrhbn_8r0000gn/T/pip-req-build-zn0v_x_c/.eggs/charset_normalizer-3.1.0-py3.10-macosx-10.9-universal2.egg/EGG-INFO'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pynput
  Running setup.py clean for pynput
  error: subprocess-exited-with-error
  
  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      /Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/33/g_h_rt791rvdrpm4xrhbn_8r0000gn/T/pip-req-build-zn0v_x_c/setup.py", line 87, in <module>
          setuptools.setup(
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 875, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1087, in obtain
          return installer(requirement)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 945, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
          wheel.install_as_egg(dist_location)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 110, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 118, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 162, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/var/folders/33/g_h_rt791rvdrpm4xrhbn_8r0000gn/T/pip-req-build-zn0v_x_c/.eggs/charset_normalizer-3.1.0-py3.10-macosx-10.9-universal2.egg/charset_normalizer-3.1.0.dist-info' -> '/private/var/folders/33/g_h_rt791rvdrpm4xrhbn_8r0000gn/T/pip-req-build-zn0v_x_c/.eggs/charset_normalizer-3.1.0-py3.10-macosx-10.9-universal2.egg/EGG-INFO'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for pynput
Failed to build pynput

How do I resolve this?
ChatGPT: The error you're encountering is related to the installation of the pynput package. It seems there's an issue with the charset_normalizer package that's causing the build to fail. To resolve this issue, you can try the following steps:Upgrade pip, setuptools, and wheel:bashCopy codepython -m pip install --upgrade pip setuptools wheel
Try installing the pynput package again:bashCopy codepython -m pip install pynput
If the problem persists, you can try installing charset_normalizer separately before installing pynput:Install charset_normalizer:bashCopy codepython -m pip install charset_normalizer
Install pynput:bashCopy codepython -m pip install pynput
If the issue still persists, there might be a compatibility issue with your Python version or your operating system. In that case, you may want to consider using a different version of Python or reaching out to the developers of the pynput package for assistance.
Human: When I run:

python -m pip install --upgrade pip setuptools wheel

I get this error:

zsh: command not found: python
ChatGPT: It looks like the python command is not recognized by your system. You might be using a different command for running Python on your system, such as python3 or python3.10.Try running the same command using python3:bashCopy codepython3 -m pip install --upgrade pip setuptools wheel
If that still doesn't work, try using the specific version, like python3.10:bashCopy codepython3.10 -m pip install --upgrade pip setuptools wheel
In case none of these commands work, you may need to add the Python executable to your system's PATH or check if Python is installed correctly on your system. You can check the installed Python version by running:bashCopy codepython3 --version
orbashCopy codepython3.10 --version
If Python is not installed, you can download it from the official website: https://www.python.org/downloads/
Human: When I run:

python3 -m pip install --upgrade pip setuptools wheel

I get this output:

Requirement already satisfied: pip in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (23.1.2)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (67.7.2)
Requirement already satisfied: wheel in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (0.40.0)
ChatGPT: Great! This output means that pip, setuptools, and wheel are already installed and up-to-date in your Python 3.11 environment. You can now proceed with installing other packages or running your Python scripts without any issues related to these packages.If you still face issues when installing the pynput package, you can try to install it again using:bashCopy codepython3 -m pip install pynput
If the problem persists, please provide the error message, and I'll be happy to help you further.
Human: After running:

python3 -m pip install pynput

I get this output:

Collecting pynput
  Using cached pynput-1.7.6-py2.py3-none-any.whl (89 kB)
Collecting six (from pynput)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting pyobjc-framework-ApplicationServices>=8.0 (from pynput)
  Downloading pyobjc_framework_ApplicationServices-9.1.1-cp311-cp311-macosx_10_9_universal2.whl (32 kB)
Collecting pyobjc-framework-Quartz>=8.0 (from pynput)
  Downloading pyobjc_framework_Quartz-9.1.1-cp311-cp311-macosx_10_9_universal2.whl (228 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 228.4/228.4 kB 4.7 MB/s eta 0:00:00
Collecting pyobjc-core>=9.1.1 (from pyobjc-framework-ApplicationServices>=8.0->pynput)
  Downloading pyobjc_core-9.1.1-cp311-cp311-macosx_10_9_universal2.whl (730 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 730.2/730.2 kB 14.1 MB/s eta 0:00:00
Collecting pyobjc-framework-Cocoa>=9.1.1 (from pyobjc-framework-ApplicationServices>=8.0->pynput)
  Downloading pyobjc_framework_Cocoa-9.1.1-cp311-cp311-macosx_10_9_universal2.whl (390 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 390.5/390.5 kB 9.7 MB/s eta 0:00:00
Installing collected packages: six, pyobjc-core, pyobjc-framework-Cocoa, pyobjc-framework-Quartz, pyobjc-framework-ApplicationServices, pynput
Successfully installed pynput-1.7.6 pyobjc-core-9.1.1 pyobjc-framework-ApplicationServices-9.1.1 pyobjc-framework-Cocoa-9.1.1 pyobjc-framework-Quartz-9.1.1 six-1.16.0
ChatGPT: Great! The output shows that the pynput package and its dependencies have been successfully installed in your Python environment. You should now be able to use pynput in your Python scripts without any issues.You can test it by creating a simple Python script that imports the pynput package, like this:pythonCopy codefrom pynput import keyboard

def on_press(key):
    print(f'Key pressed: {key}')

def on_release(key):
    print(f'Key released: {key}')
    if key == keyboard.Key.esc:
        return False

with keyboard.Listener(on_press=on_press, on_release=on_release) as listener:
    listener.join()
Save the script in a file named test_pynput.py and run it using:bashCopy codepython3 test_pynput.py
This script will print the keys you press and release. Press the Esc key to exit the script. If the script runs without any issues, it means pynput is working correctly in your environment.
```

**Comment by abrichr** [comment]
@Jonathan-Sendsen did we resolve this during our phone conversation? If not, the issue is with pynput. We use a non-standard version. You have to install from the requirements text file. If that doesn’t work, please provide the full console output.

**Comment by Jonathan-Sendsen** [comment]
Can confirm this issue is resolved. Thanks!
